config/routes.rb
require 'year_constraint'
require 'api_constraints'

Rails.application.routes.draw do

  default_url_options protocol: '//' # HTTP o HTTPS
  default_url_options host: Rails.application.secrets.rails_host

  namespace :api, defaults: {format: :json}, except: [:new, :edit] do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do

      resources :nota_entradas, only: [:index] do
        put :anular, on: :member
      end

      resources :solicitudes, only: [:index] do
        put :anular, on: :member
      end

      resources :users, only: [:obt_historico_actas] do
        get :obt_historico_actas, on: :member
        get :obt_activos, on: :member
      end

      resources :reportes, only: [:activos] do
        get :activos, on: :collection
      end

      resources :seguros, only: [:create, :update]

      resources :proveedores, only: [:index]

      resources :activos, only: [:index] do
        get :sin_seguro_vigente, on: :member
      end

      resources :requests, only: [:show] do
        post :validar_cantidades, on: :member
      end

      resources :auxiliares, only: [:show]

      resources :accounts, only: [:show]

      resources :suppliers, only: [:show]

      resources :materiales, only: [:index] do
        get :subarticulos, on: :member
      end

    end
    namespace :v2, constraints: ApiConstraints.new(version: 2, default: true) do
      get '/estado', to: 'estado#index', as: :estado
      get '/almacenes/articulos' => 'almacenes#articulos', as: :articulos_almacenes
      get '/almacenes/solicitud' => 'almacenes#obtener_solicitud', as: :obtener_solicitud_almacenes
      post '/almacenes/solicitud' => 'almacenes#crear_solicitud', as: :crear_solicitud_almacenes
      patch '/almacenes/solicitud' => 'almacenes#actualizar_solicitud', as: :actualizar_solicitud_almacenes
      get '/almacenes/proveedores' => 'almacenes#proveedores', as: :proveedores_almacenes
      post '/almacenes/ingreso' => 'almacenes#crear_nuevo_ingreso', as: :crear_nuevo_ingreso_almacenes

      get '/activos/usuario/:usuario', to: 'activos#activos_funcionario', as: :activos_funcionario_activos
      get '/activos/buscar', to: 'activos#buscar', as: :buscar_activos
      post '/activos/devolucion', to: 'activos#devolucion', as: :devolucion_activos
      post '/activos/asignacion', to: 'activos#asignacion', as: :asignacion_activos
      get '/activos/ubicaciones', to: 'activos#ubicaciones', as: :ubicaciones_activos
      get '/activos/auxiliares', to: 'activos#auxiliares', as: :auxiliares_activos
      get '/activos/estados', to: 'activos#estados', as: :estados_activos
      get '/activos/proveedores', to: 'activos#proveedores', as: :proveedores_activos
      post '/activos/ingreso', to: 'activos#crear_nuevo_ingreso', as: :crear_nuevo_ingreso_activos
      post '/activos/baja', to: 'activos#baja', as: :baja_activos

      namespace :almacenes do
        resources :ingresos, only: [:update]
        resources :reportes, only: [] do
          post :fisico_valorado, on: :collection
          post :fisico_valorado_pdf, on: :collection
          post :fisico_valorado_ods_csv, on: :collection
        end
      end
    end
  end

  resources :gestiones, except: [:destroy] do
    put 'cerrar', on: :member
  end
  resources :ufvs, except: [:show, :destroy]
  resources :ubicaciones, except: [:show, :destroy]
  resources :ingresos do
    get :obt_cod_ingreso, on: :collection
  end

  resources :reportes do
    collection do
      get :kardex
      get :activos
      get :depreciacion
      get :resumen
      get :cuenta_contable
      get :inventario_fisico_valorado_v2
      get :estadisticas
      get :bajas
    end
  end

  resources :entry_subarticles, only: [:edit, :update]

  resources :note_entries, except: [:destroy] do
    get :get_suppliers, on: :collection
    get :obt_cod_ingreso, on: :collection
  end

  resources :suppliers do
    get :note_entries, on: :member
    get :ingresos, on: :member
  end

  resources :accounts do
    get :auxiliares, on: :member
    get :activos, on: :member
  end

  resources :seguros do
    get :asegurar, on: :member
    get :incorporaciones, on: :member
    get :activos, on: :member
    get :resumen, on: :member
  end

  resources :bajas, only: [:index, :new, :create, :show, :edit]

  resources :requests, except: [:edit, :destroy] do
    get :obtiene_nro_solicitud, on: :collection
  end

  resources :materials, except: [:destroy] do
    post :change_status, on: :member
    get :reports, on: :collection
    post :fisico_valorado, on: :collection
  end

  resources :subarticles, except: [:destroy] do
    resources :kardexes, only: [:index]

    member do
      post :change_status
      get :kardex_v2
    end
    collection do
      get :get_subarticles
      get :autocomplete
      post :first_entry
    end
  end

  resources :barcodes, only: [:index] do
    collection do
      get :obt_cod_barra
      post :pdf
    end
  end

  resources :proceedings, only: [:index, :show, :create, :update]

  resources :declines, only: [:index]

  resources :versions, only: [:index] do
    post :export, on: :collection
  end

  resources :assets, except: [:destroy] do
    member do
      get :historical
      get :depreciacion
    end
    collection do
      get :autocomplete
      get :admin_assets
      get :search
      get :assignation
      get :devolution
      get :users
      get :departments
    end
  end

  resources :auxiliaries, except: [:destroy] do
    post :change_status, on: :member
    get :activos, on: :member
  end

  resources :accounts, only: [:index, :show] do
    post :change_status, on: :member
  end

  resources :departments, except: [:destroy] do
    post :change_status, on: :member
    get :download, on: :member
  end

  resources :buildings, except: [:destroy] do
    post :change_status, on: :member
  end

  resources :api_tokens, except: [:destroy] do
    post :change_status, on: :member
  end

  resources :entities

  resources :users, except: [:destroy] do
    post :change_status, on: :member
    get :welcome, on: :collection
    get :download, on: :member
    get :autocomplete, on: :collection
    get :historical, on: :member
    get :historico_almacen, on: :member
    get :verificar_usuario, on: :collection
    get :ver_duplicados, on: :collection
    get :ver_ci_incongruentes, on: :collection
    get :verificar_campo, on: :collection
    post :agrupacion_usuario, on: :collection
    post :guardar_agrupacion, on: :collection
    post :eliminar_usuario, on: :collection
  end

  get '/datatables-spanish', to: 'welcome#datatables_spanish', as: :spanish_datatables
  get '/dashboard', to: 'dashboard#index', as: :dashboard
  patch '/dashboard/update_password', to: 'dashboard#update_password', as: :update_password_dashboard
  post '/dashboard/announcements/hide', to: 'dashboard#hide', as: :hide_announcement

  post '/dbf/:model/import', to: 'dbf#import', constraints: { model: /(buildings|departments|users|accounts|auxiliaries|assets)/ }, as: 'import_dbf'
  get '/dbf/:model', to: 'dbf#index', constraints: { model: /(buildings|departments|users|accounts|auxiliaries|assets)/ }, as: 'dbf'
  get '/dbf', to: redirect("#{ Rails.application.config.action_controller.relative_url_root }/dbf/buildings"), as: 'migration'

  devise_for :users, controllers: { sessions: "sessions" }, skip: [ :sessions ]
  as :user do
    get '/login' => 'sessions#new', as: :new_user_session
    post '/login' => 'sessions#create', as: :user_session
    delete '/logout' => 'sessions#destroy', as: :destroy_user_session
  end

  resources :welcome, only: [:index]

  root 'users#welcome'
end

app/views/shared/_admin.html.haml
.col-sm-6
  %table.table.table-condensed.table-striped.table-bordered
    %tbody
      %tr
        %td #{t('buildings.title.title')}
        %td.number= number_with_delimiter Building.count
      %tr
        %td #{t('departments.title.title')}
        %td.number
          %span= number_with_delimiter Department.count
      %tr
        %td #{t('users.title.title')}
        %td.number
          %span= number_with_delimiter User.count

app/views/shared/_alertas.html.haml
- if @activos_sin_seguro.present? && @activos_sin_seguro > 0
  %div{class: "pull-right"}
    %div{ style: "margin-right: 20px;", class: "alert alert-danger blink" }
      %button.close{"data-dismiss" => "alert", type: "button"}>
        %span{"aria-hidden" => "true"} ×
        %span.sr-only Close
      Existen #{@activos_sin_seguro} activos sin seguro.

- if @seguros .present?
  - @seguros.each do |s|
    - if (alerta = s.alerta_expiracion).present?
      %div{ style: "margin-right: 20px;", class: "alert alert-#{alerta[:tipo]} pull-right #{alerta[:parpadeo] ? 'blink' : ''}" }
        %button.close{"data-dismiss" => "alert", type: "button"}>
          %span{"aria-hidden" => "true"} ×
          %span.sr-only Close
        #{ alerta[:mensaje] }

app/views/shared/_assets.html.haml
.col-sm-6
  %table.table.table-condensed.table-striped.table-bordered
    %tbody
      %tr
        %td Activos
        %td.number= number_with_delimiter Asset.count, 0
      %tr
        %td Total histórico
        %td.number= number_with_delimiter Asset.total_historico
      - if Asset.without_user.count > 0
        %tr
          %td Activos sin funcionario
          %td.number
            %span.text-danger= number_with_delimiter Asset.without_user.count
      - if Asset.without_barcode.count > 0
        %tr
          %td Activos sin código de barras
          %td.number
            %span.text-danger= number_with_delimiter Asset.without_barcode.count

app/views/shared/_confirm_modal.html.haml
%script{ id: 'destroy-modal', type: 'text/html' }
  .modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1", id: "modal-{{domId}}"}
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
          %h4.modal-title {{{title}}}
        .modal-body
          .title_message {{{confirmMessage}}}
          - if controller_name == 'assets'
            = form_tag "{{url}}", class: 'form-horizontal' do
              .form-group
                %label.col-sm-2.control-label= Asset.human_attribute_name('description_decline')
                .col-sm-10
                  = text_area_tag "asset[description_decline]", '', class: 'form-control'
              .form-group
                %label.col-sm-2.control-label= Asset.human_attribute_name('reason_decline')
                .col-sm-10
                  = text_area_tag "asset[reason_decline]", '', class: 'form-control'
          {{#entry}}
          = simple_form_for EntrySubarticle.new, url: first_entry_subarticles_path, html: { class: 'form-horizontal form_entry', id: "form_entry_{{id}}" } do |f|
            = render 'subarticles/new_entry', id: 0, subarticle_id: "{{id}}", is_first: true
            = link_to '#', class: "new_entry" do
              %span.glyphicon.glyphicon-plus
              Agregar Saldo
          {{/entry}}
        .modal-footer
          %button.btn.btn-default{"data-dismiss" => "modal", type: "button"}= t('general.btn.cancel')
          {{#entry}}
          = button_tag t('general.btn.save'), class: 'btn btn-primary', id: 'new_entry'
          {{/entry}}
          {{#unassigned}}
          - if controller_name == 'assets'
            = button_tag t('general.btn.save'), class: 'btn btn-primary deregister'
          - else
            = link_to t('general.btn.save'), "{{url}}", class: 'btn btn-primary change_status', method: :post, remote: true
          {{/unassigned}}

- if controller_name == 'subarticles'
  %script{ id: 'entry_subarticle', type: 'text/html', data: {action: 'subarticulos'} }
    .modal-header{ style: 'margin-bottom: 5px;' }
    = render 'subarticles/new_entry'

- if controller_name == 'requests'
  %script{ id: 'editar-solicitud-tpl', type: 'text/html' }
    .modal-header{ style: 'margin-bottom: 5px;' }
    = render 'requests/editar'

- if controller_name == 'note_entries'
  %script{ id: 'editar-nota-entrada-tpl', type: 'text/html' }
    .modal-header{ style: 'margin-bottom: 5px;' }
    = render 'note_entries/editar'

- if controller_name == 'ingresos'
  %script{ id: 'editar-nota-entrada-tpl', type: 'text/html' }
    .modal-header{ style: 'margin-bottom: 5px;' }
    = render 'ingresos/editar'

- if controller_name == 'proceedings'
  %script{ id: 'editar-acta-tpl', type: 'text/html' }
    .modal-header{ style: 'margin-bottom: 5px;' }
    = render 'proceedings/editar'

app/views/shared/_derecognised.html.haml
.col-sm-6
  %table.table.table-condensed.table-striped.table-bordered
    %tbody
      %tr
        %td Actas
        %td.number= number_with_delimiter Proceeding.count
      %tr
        %td Actas de Asignación
        %td.number= number_with_delimiter Proceeding.assignation.count
      %tr
        %td Actas de Devolución
        %td.number
          %span= number_with_delimiter Proceeding.devolution.count
      %tr
        %td Activos dados de baja
        %td.number
          %span= number_with_delimiter Asset.bajas.count

app/views/shared/_form_buttons.html.haml
- case controller_name
- when 'users' then list_url = user.id == current_user.id ? user : users_path
- when 'departments' then list_url = departments_path
- when 'buildings' then list_url = buildings_path
- when 'entities' then list_url = entities_path
- when 'accounts' then list_url = accounts_path
- when 'auxiliaries' then list_url = auxiliaries_path
- when 'assets' then list_url = URI(request.referer || assets_path).path
- when 'materials' then list_url = materials_path
- when 'articles' then list_url = articles_path
- when 'subarticles' then list_url = subarticles_path
- when 'suppliers' then list_url = suppliers_path
- when 'note_entries' then list_url = note_entries_path

.form-group
  .col-sm-offset-5.col-sm-9
    = submit_and_cancel(list_url || :back)

app/views/shared/footer.pdf.haml
#footer
  = img_pdf('footer')

app/views/shared/header.pdf.haml
#header
  = img_pdf('header')

app/views/shared/header_horizontal.pdf.haml
#header-horizontal
  = img_pdf('header')

app/views/shared/index.html.haml
- case controller_name
- when 'entities' then new_url = new_entity_path if @entities.blank?
- when 'users' then new_url = new_user_path
- when 'departments' then new_url = new_department_path
- when 'buildings' then new_url = new_building_path
- when 'auxiliaries' then new_url = new_auxiliary_path
- when 'accounts' then new_url = new_account_path
- when 'assets' then new_url = new_asset_path
- when 'versions' then new_url = '#'
- when 'materials' then new_url = new_material_path
- when 'articles' then new_url = new_article_path
- when 'subarticles' then new_url = new_subarticle_path
- when 'suppliers' then new_url = new_supplier_path
- when 'requests' then Rails.application.secrets.interoperabilidad_plantillas.present? ? new_url = nil : new_url = new_request_path
- when 'note_entries' then Rails.application.secrets.interoperabilidad_plantillas.present? ? new_url = nil : new_url = new_note_entry_path
- when 'ingresos' then Rails.application.secrets.interoperabilidad_plantillas.present? ? new_url = nil : new_url = new_ingreso_path
- when 'ubicaciones' then new_url = new_ubicacion_path
- when 'seguros' then new_url = new_seguro_path
- when 'ufvs' then new_url = new_ufv_path
- when 'gestiones' then new_url = new_gestion_path
- when 'proceedings' then accion = 'actas'
- when 'api_tokens' then new_url = new_api_token_path
- control = controller_name == 'bajas' ? 'bajas' : controller_name


= title t("#{control}.title.title")
- if controller_name == 'assets'
  .alertas.pull-right
    = render "shared/alertas"
.page-header{data: {action: "#{accion if accion.present?}"}}
  %h2
    - if action_name == 'delivered'
      = t("delivered.title")
    - else
      #{t("#{control}.title.title")} #{' de Activos Fijos' if controller_name == 'bajas'}
      - if control == 'requests'
        = render 'dropdown', status: params[:status]
      - if control == 'assets'
        = render 'dropdown', status: params[:status]
.col-xs-2.button_new
  %span.controller_name= controller_name
  - if can? :create, controller_name.classify.constantize
    - if new_url.present?
      - is_versions = control == 'versions'
      - disabled = is_versions ? true : false
      = link_to new_url, class: "btn #{ is_versions ? 'btn-danger remove_version' : 'btn-primary' }" , title: "#{ 'Eliminar historial seleccionado' if is_versions }", disabled: disabled do
        %span{ class: "glyphicon glyphicon-#{ is_versions ? 'remove' : 'plus' }" }
        = t("#{control}.title.new")
      - if is_versions
        #versions-export{ 'data-url' => export_versions_path }
    - if controller_name == 'bajas' && Rails.application.secrets.interoperabilidad_plantillas.present? == false
      = link_to new_baja_path, class: "btn btn-primary" do
        %span{ class: 'glyphicon glyphicon-plus' }
        Nueva Baja

#datatable-spanish{ 'data-url' => spanish_datatables_path() }

%table.table.table-striped.table-hover.datatable
  %thead
    %tr
      - unless %w(versions proceedings requests note_entries suppliers ingresos ubicaciones ufvs gestiones seguros bajas api_tokens).include?(control)
        -# - unless current_user.is_super_admin? && control == 'users'
        -#   %th= User.human_attribute_name('code')
        - unless control == 'users'
          %th= User.human_attribute_name('code')
        - if control == 'users' # && !current_user.is_super_admin?
          %th= t('activerecord.attributes.user.ci')
        - if %w(subarticles).include?(control)
          %th= Subarticle.human_attribute_name('code_old')
        - if 'assets' == control
          %th= Asset.human_attribute_name('code_old')
        %th= %w(assets materials articles subarticles).include?(control) ? Asset.human_attribute_name('description') : User.human_attribute_name('name')
      = render "#{control}/#{control}"
      - unless %w(versions).include?(control)
        %th= t('general.actions')
  %tbody

#confirm-modal
= render 'shared/confirm_modal'

- columns = control.classify.constantize
- if current_user.is_super_admin? && control == 'users'
  - columns = columns.set_columns(current_user.is_super_admin?)
- elsif control == 'requests'
  - columns = columns.set_columns(params[:status] != 'initiation' && Rails.application.secrets.interoperabilidad_plantillas.present?)
- else
  - columns = columns.set_columns
= select_tag "column", options_for_select(columns), id: 'select_column', class: 'form-control col-md-2', prompt: "Todos"

app/views/shared/welcome.html.haml
.container
  .jumbotron.j_bottom
    %p.lead
      Bienvenidos al #{title_system} #{acronym_entity}

  - if current_user.is_admin_store?
    - if minimum_stock.present?
      = render 'shared/stores/minimum_stock'
  - if current_user.is_admin?
    .row
      = render 'shared/admin'
      = render 'shared/assets'
      = render 'shared/derecognised'