config/routes.rb
require 'year_constraint'
require 'api_constraints'

Rails.application.routes.draw do

  default_url_options protocol: '//' # HTTP o HTTPS
  default_url_options host: Rails.application.secrets.rails_host

  namespace :api, defaults: {format: :json}, except: [:new, :edit] do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do

      resources :nota_entradas, only: [:index] do
        put :anular, on: :member
      end

      resources :solicitudes, only: [:index] do
        put :anular, on: :member
      end

      resources :users, only: [:obt_historico_actas] do
        get :obt_historico_actas, on: :member
        get :obt_activos, on: :member
      end

      resources :reportes, only: [:activos] do
        get :activos, on: :collection
      end

      resources :seguros, only: [:create, :update]

      resources :proveedores, only: [:index]

      resources :activos, only: [:index] do
        get :sin_seguro_vigente, on: :member
      end

      resources :requests, only: [:show] do
        post :validar_cantidades, on: :member
      end

      resources :auxiliares, only: [:show]

      resources :accounts, only: [:show]

      resources :suppliers, only: [:show]

      resources :materiales, only: [:index] do
        get :subarticulos, on: :member
      end

    end
    namespace :v2, constraints: ApiConstraints.new(version: 2, default: true) do
      get '/estado', to: 'estado#index', as: :estado
      get '/almacenes/articulos' => 'almacenes#articulos', as: :articulos_almacenes
      get '/almacenes/solicitud' => 'almacenes#obtener_solicitud', as: :obtener_solicitud_almacenes
      post '/almacenes/solicitud' => 'almacenes#crear_solicitud', as: :crear_solicitud_almacenes
      patch '/almacenes/solicitud' => 'almacenes#actualizar_solicitud', as: :actualizar_solicitud_almacenes
      get '/almacenes/proveedores' => 'almacenes#proveedores', as: :proveedores_almacenes
      post '/almacenes/ingreso' => 'almacenes#crear_nuevo_ingreso', as: :crear_nuevo_ingreso_almacenes

      get '/activos/usuario/:usuario', to: 'activos#activos_funcionario', as: :activos_funcionario_activos
      get '/activos/buscar', to: 'activos#buscar', as: :buscar_activos
      post '/activos/devolucion', to: 'activos#devolucion', as: :devolucion_activos
      post '/activos/asignacion', to: 'activos#asignacion', as: :asignacion_activos
      get '/activos/ubicaciones', to: 'activos#ubicaciones', as: :ubicaciones_activos
      get '/activos/auxiliares', to: 'activos#auxiliares', as: :auxiliares_activos
      get '/activos/estados', to: 'activos#estados', as: :estados_activos
      get '/activos/proveedores', to: 'activos#proveedores', as: :proveedores_activos
      post '/activos/ingreso', to: 'activos#crear_nuevo_ingreso', as: :crear_nuevo_ingreso_activos
      post '/activos/baja', to: 'activos#baja', as: :baja_activos

      namespace :almacenes do
        resources :ingresos, only: [:update]
        resources :reportes, only: [] do
          post :fisico_valorado, on: :collection
          post :fisico_valorado_pdf, on: :collection
          post :fisico_valorado_ods_csv, on: :collection
        end
      end
    end
  end

  resources :gestiones, except: [:destroy] do
    put 'cerrar', on: :member
  end
  resources :ufvs, except: [:show, :destroy]
  resources :ubicaciones, except: [:show, :destroy]
  resources :ingresos do
    get :obt_cod_ingreso, on: :collection
  end

  resources :reportes do
    collection do
      get :kardex
      get :activos
      get :depreciacion
      get :resumen
      get :cuenta_contable
      get :inventario_fisico_valorado_v2
      get :estadisticas
      get :bajas
    end
  end

  resources :entry_subarticles, only: [:edit, :update]

  resources :note_entries, except: [:destroy] do
    get :get_suppliers, on: :collection
    get :obt_cod_ingreso, on: :collection
  end

  resources :suppliers do
    get :note_entries, on: :member
    get :ingresos, on: :member
  end

  resources :accounts do
    get :auxiliares, on: :member
    get :activos, on: :member
  end

  resources :seguros do
    get :asegurar, on: :member
    get :incorporaciones, on: :member
    get :activos, on: :member
    get :resumen, on: :member
  end

  resources :bajas, only: [:index, :new, :create, :show, :edit]

  resources :requests, except: [:edit, :destroy] do
    get :obtiene_nro_solicitud, on: :collection
  end

  resources :materials, except: [:destroy] do
    post :change_status, on: :member
    get :reports, on: :collection
    post :fisico_valorado, on: :collection
  end

  resources :subarticles, except: [:destroy] do
    resources :kardexes, only: [:index]

    member do
      post :change_status
      get :kardex_v2
    end
    collection do
      get :get_subarticles
      get :autocomplete
      post :first_entry
    end
  end

  resources :barcodes, only: [:index] do
    collection do
      get :obt_cod_barra
      post :pdf
    end
  end

  resources :proceedings, only: [:index, :show, :create, :update]

  resources :declines, only: [:index]

  resources :versions, only: [:index] do
    post :export, on: :collection
  end

  resources :assets, except: [:destroy] do
    member do
      get :historical
      get :depreciacion
    end
    collection do
      get :autocomplete
      get :admin_assets
      get :search
      get :assignation
      get :devolution
      get :users
      get :departments
    end
  end

  resources :auxiliaries, except: [:destroy] do
    post :change_status, on: :member
    get :activos, on: :member
  end

  resources :accounts, only: [:index, :show] do
    post :change_status, on: :member
  end

  resources :departments, except: [:destroy] do
    post :change_status, on: :member
    get :download, on: :member
  end

  resources :buildings, except: [:destroy] do
    post :change_status, on: :member
  end

  resources :api_tokens, except: [:destroy] do
    post :change_status, on: :member
  end

  resources :entities

  resources :users, except: [:destroy] do
    post :change_status, on: :member
    get :welcome, on: :collection
    get :download, on: :member
    get :autocomplete, on: :collection
    get :historical, on: :member
    get :historico_almacen, on: :member
    get :verificar_usuario, on: :collection
    get :ver_duplicados, on: :collection
    get :ver_ci_incongruentes, on: :collection
    get :verificar_campo, on: :collection
    post :agrupacion_usuario, on: :collection
    post :guardar_agrupacion, on: :collection
    post :eliminar_usuario, on: :collection
  end

  get '/datatables-spanish', to: 'welcome#datatables_spanish', as: :spanish_datatables
  get '/dashboard', to: 'dashboard#index', as: :dashboard
  patch '/dashboard/update_password', to: 'dashboard#update_password', as: :update_password_dashboard
  post '/dashboard/announcements/hide', to: 'dashboard#hide', as: :hide_announcement

  post '/dbf/:model/import', to: 'dbf#import', constraints: { model: /(buildings|departments|users|accounts|auxiliaries|assets)/ }, as: 'import_dbf'
  get '/dbf/:model', to: 'dbf#index', constraints: { model: /(buildings|departments|users|accounts|auxiliaries|assets)/ }, as: 'dbf'
  get '/dbf', to: redirect("#{ Rails.application.config.action_controller.relative_url_root }/dbf/buildings"), as: 'migration'

  devise_for :users, controllers: { sessions: "sessions" }, skip: [ :sessions ]
  as :user do
    get '/login' => 'sessions#new', as: :new_user_session
    post '/login' => 'sessions#create', as: :user_session
    delete '/logout' => 'sessions#destroy', as: :destroy_user_session
  end

  resources :welcome, only: [:index]

  root 'users#welcome'
end

app/controllers/api/v2/almacenes/ingresos_controller.rb
module Api
  module V2
    module Almacenes
      class IngresosController < ApplicationController
        skip_before_action :verify_authenticity_token
        before_action :set_ingreso, only: [:update]

        respond_to :json

        #patch ingresos(note_entries)
        def update
          respuesta, mensaje = @ingreso.actualizar(params[:ingreso].to_hash)
          render json: formato_respuesta(respuesta, mensaje, {})
        end

        private

        def set_ingreso
          @ingreso = NoteEntry.find(params[:id])
        end
      end
    end
  end
end

app/controllers/ingresos_controller.rb
class IngresosController < ApplicationController
  load_and_authorize_resource
  before_action :set_ingreso, only: [:show, :edit, :update, :destroy]
  before_action :verificar_interoperabilidad, only: [:new, :edit, :create, :update]

  # GET /ingresos
  def index
    if params[:barcode].present?
      barcode = params[:barcode]
      activos = Asset.buscar_por_barcode(barcode)
      render json: activos, root: false
    else
      format_to('ingresos', IngresosDatatable)
    end
  end

  # GET /ingresos/1
  def show
    @activos = @ingreso.assets.order(:code)
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Ingreso #{@ingreso.nota_entrega_fecha}".parameterize,
               disposition: 'attachment',
               template: 'ingresos/show.html.haml',
               layout: 'pdf.html',
               page_size: 'Letter',
               # show_as_html: params[:debug].present?,
               margin: view_context.margin_pdf,
               header: { html: { template: 'shared/header.pdf.haml' } },
               footer: { html: { template: 'shared/footer.pdf.haml' } }
      end
    end
  end

  # GET /ingresos/new
  def new
    @ingreso = Ingreso.new
  end

  # GET /ingresos/1/edit
  def edit
    render 'new'
  end

  # POST /ingresos
  def create
    @ingreso = current_user.ingresos.new(ingreso_params)
    respond_to do |format|
      if @ingreso.save
        format.html { redirect_to @ingreso, notice: 'Ingreso creado exitosamente' }
        format.json { render json: @ingreso, status: :created }
      else
        format.html { render :new }
        format.json { render json: @ingreso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingresos/1
  def update
    respond_to do |format|
      if @ingreso.update(ingreso_params)
        format.html { redirect_to @ingreso, notice: t('general.updated', model: Ingreso.model_name.human) }
        format.js
      else
        format.html { render action: 'new' }
      end
    end
  end

  def obt_cod_ingreso
    resultado = Hash.new
    if params[:d].present?
      fecha = params[:d].to_date
      if params[:n].present?
        nota_ingreso = Ingreso.find(params[:n])
        unless nota_ingreso.numero.present?
          resultado = Ingreso.obtiene_siguiente_numero_ingreso(fecha)
        end
      else
        resultado = Ingreso.obtiene_siguiente_numero_ingreso(fecha)
      end
      if resultado[:tipo_respuesta] == 'confirmacion'
        resultado[:titulo] = "Confirmación de Ingreso"
      elsif resultado[:tipo_respuesta] == 'alerta'
        resultado[:titulo] = "Alerta de Ingreso"
      end
    end
    render json: resultado, root: false
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingreso
      @ingreso = Ingreso.find(params[:id])
    end

    def verificar_interoperabilidad
      if Rails.application.secrets.interoperabilidad_plantillas.present?
        redirect_to ingresos_url, alert: 'Acceso denegado'
      end
    end

    # Only allow a trusted parameter "white list" through.
    def ingreso_params
      params.require(:ingreso).permit(:numero, :supplier_id, :factura_numero, :factura_autorizacion, :factura_fecha, :nota_entrega_numero, :nota_entrega_fecha, :c31_numero, :c31_fecha, :total, :tipo_ingreso, :entidad_donante, :observacion, asset_ids: [])
    end
end

app/views/ingresos/_editar.html.haml
.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1", id: "modal-editar-nota-entrada"}
  .modal-dialog
    .modal-content
      = form_for :ingreso, url: ingresos_path + '/{{id}}', class: 'form-horizontal', data: {id: "{{id}}"} do |f|
        .modal-header
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} &times;
          %h4.modal-title Editar nota de ingreso
        .modal-body
          = hidden_field_tag '_method', 'PUT'
          .form-group
            %label.col-sm-4.control-label Nro nota ingreso
            .col-sm-8
              = f.text_field "numero", value: "{{numero}}", class: 'form-control nro-nota-ingreso-select', autofocus: true
        .modal-footer
          %button.btn.btn-default{"data-dismiss" => "modal", type: "button"}
            %span.glyphicon.glyphicon-ban-circle
            = t('general.btn.cancel')
          %button.btn.btn-primary{type: 'submit'}
            %span.glyphicon.glyphicon-floppy-disk
            = t('general.btn.save')

app/views/ingresos/_ingreso.html.haml
- r = ingreso
%td(class="nowrap sorting_1")= r.factura_fecha.present? ? I18n.l(r.factura_fecha) : ''
%td(class="")= r.numero
%td(class="")= r.supplier_name
%td(class="")= r.user_name
%td(class="")= number_with_delimiter(r.total)
%td(class="")= r.nota_entrega_fecha.present? ? I18n.l(r.nota_entrega_fecha) : ''
%td(class="nowrap")
  = raw(links_actions(r, 'ingreso'))
  = link_to(content_tag(:span, "", class: 'glyphicon glyphicon-sort-by-order'), '#editar', class: 'btn btn-info btn-xs editar-nota-entrada', title: 'Establecer número de nota de entrada', data: {"nota-entrada" => r.as_json}, id: dom_id(r))

app/views/ingresos/_ingreso_modal.html.haml
%script{ id: 'confirmar-ingreso-tpl', type: 'text/html' }
  .modal-header{ style: 'margin-bottom: 5px;' }
  .modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1", id: "modal-confirmar-ingreso"}
    .modal-dialog
      .modal-content
        = form_for :note_entry, url: "", class: 'form-horizontal', data: "" do |f|
          .modal-header
            %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} &times;
            %h4.modal-title {{{titulo}}}
          .modal-body
            .form-group
              %p
                Se está introduciendo un ingreso con fecha anterior al
                %strong {{{ultima_fecha}}}
                , la numeración asignada será la siguiente:
              %h2.text-center
                {{{numero}}}
              %p
                Es necesario especificar una observación:
              .form-group
                = text_area_tag "modal_observacion", '', class: 'form-control'
          .modal-footer
            %button.btn.btn-default{"data-dismiss" => "modal", type: "button"}
              %span.glyphicon.glyphicon-ban-circle
              = t('general.btn.cancel')
            %button.btn.btn-primary{type: 'submit'}
              %span.glyphicon.glyphicon-ok
              = t('general.btn.aceptar')

%script{ id: 'alerta-ingreso-tpl', type: 'text/html' }
  .modal-header{ style: 'margin-bottom: 5px;' }
  .modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1", id: "modal-alerta-ingreso"}
    .modal-dialog
      .modal-content
        = form_for :note_entry, url: "", class: 'form-horizontal', data: "" do |f|
          .modal-header
            %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} &times;
            %h4.modal-title {{{titulo}}}
          .modal-body
            .form-group
              %p
                No se puede crear el ingreso con fecha {{{fecha}}}, porque el sistema no puede asignar automáticamente la numeración:
            .form-group
              %table.table.table-bordered
                %thead
                  %tr
                    %th Número
                    %th Fecha
                %tbody
                  %tr
                    %td {{{numero_ingreso_anterior}}}
                    %td {{{fecha_ingreso_anterior}}}
                  %tr.danger
                    %td
                      %strong ?
                    %td {{{fecha}}}
                  %tr
                    %td {{{numero_ingreso_posterior}}}
                    %td {{{fecha_ingreso_posterior}}}
          .modal-footer
            %button.btn.btn-primary{type: 'submit'}
              %span.glyphicon.glyphicon-ok
              = t('general.btn.aceptar')

app/views/ingresos/_ingresos.html.haml
%th= t("activerecord.attributes.ingreso.numero")
- if Rails.application.secrets.interoperabilidad_plantillas.present?
  %th= t("activerecord.attributes.ingreso.documento_cite")
%th= t("activerecord.attributes.ingreso.factura_fecha")
%th= t("activerecord.attributes.ingreso.factura_numero")
%th= t("activerecord.attributes.ingreso.supplier")
%th= t("activerecord.attributes.ingreso.telefono")
%th= t("activerecord.attributes.ingreso.users")
%th= t("activerecord.attributes.ingreso.total")
%th= t("activerecord.attributes.ingreso.nota_entrega_fecha")

app/views/ingresos/index.pdf.haml
.title_pdf
  %h3= t("#{controller_name}.title.title")

%table.table.table-condensed.table-bordered.valorado
  %thead
    %tr
      %th.text-center Nro
      %th= t("activerecord.attributes.ingreso.numero")
      %th.text-center= t("activerecord.attributes.ingreso.factura_fecha")
      %th.text-center= t("activerecord.attributes.ingreso.factura_numero")
      %th= t("activerecord.attributes.ingreso.supplier")
      %th= t("activerecord.attributes.ingreso.telefono")
      %th= t("activerecord.attributes.ingreso.users")
      %th.text-right= t("activerecord.attributes.ingreso.total")
      %th.text-center= t("activerecord.attributes.ingreso.nota_entrega_fecha")
  %tbody
    - @array.each_with_index do |ingreso, index|
      %tr
        %td.text-center= index + 1
        %td= ingreso.numero
        %td.text-center= ingreso.factura_fecha.present? ? I18n.l(ingreso.factura_fecha) : ''
        %td= ingreso.factura_numero
        %td= ingreso.supplier_name
        %td= ingreso.telefono_proveedor
        %td= ingreso.user_name
        %td.text-right= number_with_delimiter(ingreso.total)
        %td.text-center= ingreso.nota_entrega_fecha.present? ? I18n.l(ingreso.nota_entrega_fecha) : ''
    - if @array.present?
      %tr
        %th.text-right{colspan: 5} TOTAL
        %th.text-right
          = number_with_delimiter(@array.inject(0) { |s, ingreso| s + ingreso.total})
        %th

app/views/ingresos/new.html.haml
#ingresos-urls{data: {'activos' => ingresos_path, 'proveedores' => get_suppliers_note_entries_path(format: :json, q: '%QUERY')}}
#obt_ingreso-urls{data: {'obt-ingreso' => obt_cod_ingreso_ingresos_path(format: :json), 'ingreso' => @ingreso.id}}

.row{data: {action: 'ingresos'}}
  .col-md-12
    %h3.text-center Ingreso de Activos Fijos

%form#factura-form.form-horizontal{role: 'form'}
  .form-group
    %label.col-sm-2.control-label Tipo de ingreso
    .col-sm-6.tipo-ingreso
      = radio_button_tag :tipo_ingreso, 'compra', false, class: "form-check-input"
      = label_tag 'compra', 'Compra', class: 'form-check-label mr-4'
      = radio_button_tag :tipo_ingreso, 'donacion_transferencia', false, class: "form-check-input"
      = label_tag 'donacion_transferencia', 'Donación y/o Transferencia', class: 'form-check-label'
      = radio_button_tag :tipo_ingreso, 'reposicion', false, class: "form-check-input"
      = label_tag 'reposicion', 'Reposición', class: 'form-check-label'
  #content-donante.form-group
    %label.col-sm-2.control-label Entidad donante
    .col-sm-3
      = text_field_tag 'entidad_donante', @ingreso.entidad_donante, class: 'form-control', placeholder: 'Entidad donante'
  #content-proveedor.form-group
    %label.col-sm-2.control-label Proveedor
    .col-sm-3
      = text_field_tag 'proveedor', @ingreso.supplier_name, class: 'form-control proveedor-auto', placeholder: 'Proveedor'
    .col-sm-3
      = text_field_tag 'nit', @ingreso.supplier_nit, class: 'form-control', placeholder: 'NIT proveedor', disabled: true
    .col-sm-3
      = hidden_field_tag 'telefono', @ingreso.supplier_telefono
  #content-factura.form-group
    %label.col-sm-2.control-label Factura/Doc. Respaldo
    .col-sm-3
      = text_field_tag 'factura_numero', @ingreso.factura_numero, class: 'form-control', placeholder: 'Número de factura/respaldo'
    #content-factura-autorizacion.col-sm-3
      = text_field_tag 'factura_autorizacion', @ingreso.factura_autorizacion, class: 'form-control', placeholder: 'Número autorización'
    .col-sm-3
      .input-group
        = text_field_tag 'factura_fecha', format_date(@ingreso.factura_fecha), class: 'form-control date', placeholder: 'Fecha factura/respaldo'
        .input-group-addon
          %span.glyphicon.glyphicon-calendar
  #content-nota.form-group
    %label.col-sm-2.control-label Nota de entrega
    .col-sm-3
      = text_field_tag 'nota_entrega_numero', @ingreso.nota_entrega_numero, class: 'form-control', placeholder: 'Número de nota de entrega'
    .col-sm-3
      .input-group
        = text_field_tag 'nota_entrega_fecha', format_date(@ingreso.nota_entrega_fecha), class: 'form-control date', placeholder: 'Fecha nota de entrega'
        .input-group-addon
          %span.glyphicon.glyphicon-calendar
  #content-requerimiento.form-group
    %label.col-sm-2.control-label Nº requerimiento/Nº preventivo
    .col-sm-3
      = text_field_tag 'c31_numero', @ingreso.c31_numero, class: 'form-control', placeholder: 'Nº requerimiento/Nº preventivo'
    .col-sm-3
      .input-group
        = text_field_tag 'c31_fecha', format_date(@ingreso.c31_fecha), class: 'form-control date', placeholder: 'Fecha Nº requerimiento/Nº preventivo'
        .input-group-addon
          %span.glyphicon.glyphicon-calendar
  .form-group
    %label.col-sm-2.control-label Observaciones
    .col-sm-6
      = text_area_tag :observacion, @ingreso.observacion, class: 'form-control', placeholder: 'Ingrese las observaciones y/o información adicional'

.row
  .col-md-12.col-sm-12
    %form#ingresos-form{role: 'form'}
      .row.has-success
        .col-md-offset-2.col-sm-offset-2.col-xs-offset-2.col-md-6.col-sm-6.col-xs-6
          = text_field_tag :code, '', class: 'form-control input-lg', placeholder: 'Código de Barras de Activos Fijos (ej. 1-10, 12-15, 17, 20, ...)', autofocus: true
        .col-md-3.col-sm-3.col-xs-3
          = button_tag class: 'btn btn-success btn-lg' do
            %span.glyphicon.glyphicon-search
            Buscar
          = button_tag type: 'button', class: 'btn btn-warning btn-lg', id: 'btn-clear' do
            %span.glyphicon.glyphicon-refresh
            Limpiar

%br/

%table#ingresos-tbl.table.table-bordered.table-striped.table-hover.table-condensed

%table#proveedor-tbl.table.table-bordered.table-striped.table-hover.table-condensed

-# TODO aún no está completo la funcionalidad de editar la nota de ingreso
-# de activos fijos
- if action_name != 'edit'
  .row
    .col-md-12.col-sm-12.text-center
      = link_to ingresos_path, class: 'btn btn-danger cancelar-btn' do
        %span.glyphicon.glyphicon-ban-circle
        Cancelar

      = button_tag class: 'btn btn-primary guardar-btn', data: {disable_with: 'Guardando...'} do
        %span.glyphicon.glyphicon-floppy-save
        Guardar

#confirm-modal
= render 'ingreso_modal'

%script{type: 'text/html', id: 'tpl-activo-seleccionado'}
  %thead
    %tr
      %th.text-center
        %strong.badge{title: 'Total'} {{cantidad}}
      %th.text-center Código
      %th Descripción
      %th.number Precio Unit.
  %tbody
    {{#activos}}
    %tr
      %td.text-center {{indice}}
      %td.text-center {{barcode}}
      %td {{description}}
      %td.number {{precio_formato}}
    {{/activos}}
  %tfoot
    %tr
      %th{colspan: 2}
      %th.number TOTAL
      %th.number {{total}}

app/views/ingresos/show.html.haml
- unless is_pdf?
  .page-header
    .pull-right
      - unless Rails.application.secrets.interoperabilidad_plantillas.present?
        = link_to edit_ingreso_path(@ingreso), class: 'btn btn-primary' do
          %span.glyphicon.glyphicon-edit
          = t("general.btn.edit")
      = link_to ingreso_path(@ingreso, format: :pdf), class: 'btn btn-info' do
        %span.glyphicon.glyphicon-print
        Imprimir PDF
      = link_to ingresos_path, class: 'btn btn-default' do
        %span.glyphicon.glyphicon-list
        = t("ingresos.title.title")

    %h2 Ingreso de Activos Fijos Nro. #{@ingreso.obtiene_numero}

- lista_de_campos = listar_campos(@activos)

- if is_pdf?
  .row{data: {action: 'devolution'}}
    .col-md-12
      %h3
        .text-left.proceeding-title Nro. #{@ingreso.obtiene_numero}
        .text-center Ingreso de Activos Fijos
      - if @ingreso.factura_fecha.present?
        %p
          .text-center
            Fecha de Incorporación: #{I18n.l @ingreso.factura_fecha}

%table.table.table-bordered.table-striped.table-hover.table-condensed.valorado
  %thead
    %tr
      %th.text-center Nro
      %th.text-center Cuenta
      %th.text-center Código
      - lista_de_campos.each do |campo|
        %th= Ingreso.human_attribute_name(campo)
      %th.number.nowrap Precio Unit.
  %tbody
    - @activos.each_with_index do |activo, index|
      %tr
        %td.text-center= index + 1
        %td.text-center= activo.account_name
        %td.text-center{title: activo.barcode}= activo.barcode
        - lista_de_campos.each do |campo|
          %td= activo[campo]
        %td.number= number_with_delimiter activo.precio
    %tr
      %th{ colspan: lista_de_campos.length+2 }
      %th.number TOTAL
      %th.number= number_with_delimiter @ingreso.total

%table.table.table-bordered.table-condensed.valorado{ class: "#{is_pdf? ? 'margen' : 'table-striped'}" }
  %thead
    %tr
      %th.col-md-6.col-sm-7.col-xs-8 Datos proveedor
      %th.col-md-6.col-sm-5.col-xs-4 Firma Activos Fijos
  %tbody
    %tr
      %td
        %table.table-condensed
          %tbody
            - if @ingreso.tipo_ingreso.present?
              %tr
                %th.text-right Tipo de ingreso
                %td= t("activerecord.attributes.ingreso.#{@ingreso.tipo_ingreso}")
            - if @ingreso.supplier_name.present?
              %tr
                %th.text-right Proveedor
                %td= @ingreso.supplier_name
            - if @ingreso.supplier_nit.present?
              %tr
                %th.text-right NIT
                %td= @ingreso.supplier_nit
            - if @ingreso.factura_numero.present?
              %tr
                %th.text-right Número factura/Doc. respaldo
                %td= @ingreso.factura_numero
            - if @ingreso.factura_autorizacion.present?
              %tr
                %th.text-right Autorización
                %td= @ingreso.factura_autorizacion
            - if @ingreso.factura_fecha.present?
              %tr
                %th.text-right Fecha de factura/Doc. respaldo
                %td= I18n.l @ingreso.factura_fecha
            - if @ingreso.nota_entrega_numero.present?
              %tr
                %th.text-right Número nota de entrega
                %td= @ingreso.nota_entrega_numero
            - if @ingreso.nota_entrega_fecha.present?
              %tr
                %th.text-right Fecha nota de entrega
                %td= I18n.l @ingreso.nota_entrega_fecha
            - if @ingreso.c31_numero.present?
              %tr
                %th.text-right Nº requerimiento/Nº preventivo
                %td= @ingreso.c31_numero
            - if @ingreso.c31_fecha.present?
              %tr
                %th.text-right Fecha Nº requerimiento/Nº preventivo
                %td= I18n.l @ingreso.c31_fecha
            - if @ingreso.entidad_donante.present?
              %tr
                %th.text-right Entidad donante
                %td= @ingreso.entidad_donante
            - if @ingreso.observacion.present?
              %tr
                %th.text-right Observación
                %td= @ingreso.observacion
            - if Rails.application.secrets.interoperabilidad_plantillas.present?
              %tr
                %th.text-right CITE Plantillas
                %td= @ingreso.documento_cite

      %td

= fecha_impresion if is_pdf?

app/views/ingresos/update.js.haml
var $tr = $("##{dom_id(@ingreso)}").closest('tr');

$tr.html("#{ j render @ingreso }");
$tr.addClass('warning');