config/routes.rb
require 'year_constraint'
require 'api_constraints'

Rails.application.routes.draw do

  default_url_options protocol: '//' # HTTP o HTTPS
  default_url_options host: Rails.application.secrets.rails_host

  namespace :api, defaults: {format: :json}, except: [:new, :edit] do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do

      resources :nota_entradas, only: [:index] do
        put :anular, on: :member
      end

      resources :solicitudes, only: [:index] do
        put :anular, on: :member
      end

      resources :users, only: [:obt_historico_actas] do
        get :obt_historico_actas, on: :member
        get :obt_activos, on: :member
      end

      resources :reportes, only: [:activos] do
        get :activos, on: :collection
      end

      resources :seguros, only: [:create, :update]

      resources :proveedores, only: [:index]

      resources :activos, only: [:index] do
        get :sin_seguro_vigente, on: :member
      end

      resources :requests, only: [:show] do
        post :validar_cantidades, on: :member
      end

      resources :auxiliares, only: [:show]

      resources :accounts, only: [:show]

      resources :suppliers, only: [:show]

      resources :materiales, only: [:index] do
        get :subarticulos, on: :member
      end

    end
    namespace :v2, constraints: ApiConstraints.new(version: 2, default: true) do
      get '/estado', to: 'estado#index', as: :estado
      get '/almacenes/articulos' => 'almacenes#articulos', as: :articulos_almacenes
      get '/almacenes/solicitud' => 'almacenes#obtener_solicitud', as: :obtener_solicitud_almacenes
      post '/almacenes/solicitud' => 'almacenes#crear_solicitud', as: :crear_solicitud_almacenes
      patch '/almacenes/solicitud' => 'almacenes#actualizar_solicitud', as: :actualizar_solicitud_almacenes
      get '/almacenes/proveedores' => 'almacenes#proveedores', as: :proveedores_almacenes
      post '/almacenes/ingreso' => 'almacenes#crear_nuevo_ingreso', as: :crear_nuevo_ingreso_almacenes

      get '/activos/usuario/:usuario', to: 'activos#activos_funcionario', as: :activos_funcionario_activos
      get '/activos/buscar', to: 'activos#buscar', as: :buscar_activos
      post '/activos/devolucion', to: 'activos#devolucion', as: :devolucion_activos
      post '/activos/asignacion', to: 'activos#asignacion', as: :asignacion_activos
      get '/activos/ubicaciones', to: 'activos#ubicaciones', as: :ubicaciones_activos
      get '/activos/auxiliares', to: 'activos#auxiliares', as: :auxiliares_activos
      get '/activos/estados', to: 'activos#estados', as: :estados_activos
      get '/activos/proveedores', to: 'activos#proveedores', as: :proveedores_activos
      post '/activos/ingreso', to: 'activos#crear_nuevo_ingreso', as: :crear_nuevo_ingreso_activos
      post '/activos/baja', to: 'activos#baja', as: :baja_activos

      namespace :almacenes do
        resources :ingresos, only: [:update]
        resources :reportes, only: [] do
          post :fisico_valorado, on: :collection
          post :fisico_valorado_pdf, on: :collection
          post :fisico_valorado_ods_csv, on: :collection
        end
      end
    end
  end

  resources :gestiones, except: [:destroy] do
    put 'cerrar', on: :member
  end
  resources :ufvs, except: [:show, :destroy]
  resources :ubicaciones, except: [:show, :destroy]
  resources :ingresos do
    get :obt_cod_ingreso, on: :collection
  end

  resources :reportes do
    collection do
      get :kardex
      get :activos
      get :depreciacion
      get :resumen
      get :cuenta_contable
      get :inventario_fisico_valorado_v2
      get :estadisticas
      get :bajas
    end
  end

  resources :entry_subarticles, only: [:edit, :update]

  resources :note_entries, except: [:destroy] do
    get :get_suppliers, on: :collection
    get :obt_cod_ingreso, on: :collection
  end

  resources :suppliers do
    get :note_entries, on: :member
    get :ingresos, on: :member
  end

  resources :accounts do
    get :auxiliares, on: :member
    get :activos, on: :member
  end

  resources :seguros do
    get :asegurar, on: :member
    get :incorporaciones, on: :member
    get :activos, on: :member
    get :resumen, on: :member
  end

  resources :bajas, only: [:index, :new, :create, :show, :edit]

  resources :requests, except: [:edit, :destroy] do
    get :obtiene_nro_solicitud, on: :collection
  end

  resources :materials, except: [:destroy] do
    post :change_status, on: :member
    get :reports, on: :collection
    post :fisico_valorado, on: :collection
  end

  resources :subarticles, except: [:destroy] do
    resources :kardexes, only: [:index]

    member do
      post :change_status
      get :kardex_v2
    end
    collection do
      get :get_subarticles
      get :autocomplete
      post :first_entry
    end
  end

  resources :barcodes, only: [:index] do
    collection do
      get :obt_cod_barra
      post :pdf
    end
  end

  resources :proceedings, only: [:index, :show, :create, :update]

  resources :declines, only: [:index]

  resources :versions, only: [:index] do
    post :export, on: :collection
  end

  resources :assets, except: [:destroy] do
    member do
      get :historical
      get :depreciacion
    end
    collection do
      get :autocomplete
      get :admin_assets
      get :search
      get :assignation
      get :devolution
      get :users
      get :departments
    end
  end

  resources :auxiliaries, except: [:destroy] do
    post :change_status, on: :member
    get :activos, on: :member
  end

  resources :accounts, only: [:index, :show] do
    post :change_status, on: :member
  end

  resources :departments, except: [:destroy] do
    post :change_status, on: :member
    get :download, on: :member
  end

  resources :buildings, except: [:destroy] do
    post :change_status, on: :member
  end

  resources :api_tokens, except: [:destroy] do
    post :change_status, on: :member
  end

  resources :entities

  resources :users, except: [:destroy] do
    post :change_status, on: :member
    get :welcome, on: :collection
    get :download, on: :member
    get :autocomplete, on: :collection
    get :historical, on: :member
    get :historico_almacen, on: :member
    get :verificar_usuario, on: :collection
    get :ver_duplicados, on: :collection
    get :ver_ci_incongruentes, on: :collection
    get :verificar_campo, on: :collection
    post :agrupacion_usuario, on: :collection
    post :guardar_agrupacion, on: :collection
    post :eliminar_usuario, on: :collection
  end

  get '/datatables-spanish', to: 'welcome#datatables_spanish', as: :spanish_datatables
  get '/dashboard', to: 'dashboard#index', as: :dashboard
  patch '/dashboard/update_password', to: 'dashboard#update_password', as: :update_password_dashboard
  post '/dashboard/announcements/hide', to: 'dashboard#hide', as: :hide_announcement

  post '/dbf/:model/import', to: 'dbf#import', constraints: { model: /(buildings|departments|users|accounts|auxiliaries|assets)/ }, as: 'import_dbf'
  get '/dbf/:model', to: 'dbf#index', constraints: { model: /(buildings|departments|users|accounts|auxiliaries|assets)/ }, as: 'dbf'
  get '/dbf', to: redirect("#{ Rails.application.config.action_controller.relative_url_root }/dbf/buildings"), as: 'migration'

  devise_for :users, controllers: { sessions: "sessions" }, skip: [ :sessions ]
  as :user do
    get '/login' => 'sessions#new', as: :new_user_session
    post '/login' => 'sessions#create', as: :user_session
    delete '/logout' => 'sessions#destroy', as: :destroy_user_session
  end

  resources :welcome, only: [:index]

  root 'users#welcome'
end

app/models/seguro.rb
class Seguro < ActiveRecord::Base
  include Rails.application.routes.url_helpers
  include AASM

  default_scope -> { where(baja_logica: false) }
  scope :activos, -> { where.not(baja_logica: nil) }

  belongs_to :user, dependent: :destroy
  belongs_to :supplier, dependent: :destroy
  has_and_belongs_to_many :assets
  has_many :incorporaciones, class_name: 'Seguro',
                             foreign_key: 'seguro_id'
  belongs_to :seguro, class_name: 'Seguro'

  validates :user_id, presence: true

  # validates :supplier_id, :user_id, :factura_numero, :factura_autorizacion,
  #           :factura_fecha, :fecha_inicio_vigencia, :fecha_fin_vigencia,
  #           presence: true


  aasm column: :state do
    state :cotizado, initial: true
    state :asegurado

    event :asegurar do
      transitions from: :cotizado, to: :asegurado
    end
  end

  def proveedor_nombre
    supplier.present? ? supplier.name : ''
  end

  def proveedor_nit
    supplier.present? ? supplier.nit : ''
  end

  def proveedor_telefono
    supplier.present? ? supplier.telefono : ''
  end

  def usuario_nombre
    user.present? ? user.name : ''
  end

  def vigente?(fecha_actual = DateTime.now)
    if fecha_inicio_vigencia.present? && fecha_fin_vigencia.present?
      fecha_inicio_vigencia <= fecha_actual && fecha_fin_vigencia >= fecha_actual
    else
      false
    end
  end

  def estado
    cotizado? ? "COTIZACION" : vigente? ? "VIGENTE" : "NO VIGENTE"
  end

  def cantidad_activos
    seguros_ids = [self.id] + self.incorporaciones.pluck(:id)
    "#{Asset.joins(:seguros).where(seguros: {id: seguros_ids}).uniq.size}"
  end

  # Obtiene los seguros vigentes no se toman en cuentas las incorporaciones.
  def self.vigentes(fecha_actual = DateTime.now)
    activos.where(state: 'asegurado')
           .where('fecha_inicio_vigencia <= ?', fecha_actual)
           .where('fecha_fin_vigencia >= ?', fecha_actual)
  end

  # Obtiene todo los seguros vigentes incluyendo las incorporaciones
  def self.vigentes_incorporaciones(fecha_actual = DateTime.now)
    vigentes(fecha_actual).or(activos.where(state: 'asegurado')
                                     .where(seguro_id: vigentes.ids))
  end

  def expiracion_a_dias(nro_dias)
    fecha_inicio_alerta = fecha_fin_vigencia - nro_dias
    Date.today >= fecha_inicio_alerta
  end

  def alerta_expiracion(fecha_actual=DateTime.now)
    respuesta =   {
      mensaje: "El seguro vence el #{I18n.localize fecha_fin_vigencia, format: :customize}.",
      tipo: "success",
      parpadeo: false
    }
    fin_vigencia = fecha_fin_vigencia
    inicio_vigencia = fin_vigencia - 7.days
    if fecha_actual >= inicio_vigencia && fecha_actual <= fin_vigencia
      respuesta[:parpadeo] = true
      respuesta[:tipo] = "danger"
      return respuesta
    end
    inicio_vigencia = fin_vigencia - 30.days
    if fecha_actual >= inicio_vigencia && fecha_actual <= fin_vigencia
      respuesta[:tipo] = "danger"
      return respuesta
    end
    inicio_vigencia = fin_vigencia - 90.days
    if fecha_actual >= inicio_vigencia && fecha_actual <= fin_vigencia
      respuesta[:tipo] = "warning"
      return respuesta
    end
    respuesta
  end

  def self.array_model(sort_column, sort_direction, page, per_page, sSearch, search_column, current_user = '')
    orden = "#{sort_column} #{sort_direction}"
    array = joins("LEFT JOIN suppliers ON seguros.supplier_id = suppliers.id").where(seguro_id: nil).order(orden)
    array = array.page(page).per_page(per_page) if per_page.present?
    if sSearch.present?
      if search_column.present?
        type_search = search_column == "suppliers" ? "#{search_column}.name" : "seguros.#{search_column}"
        array = array.where("#{type_search} like :search", search: "%#{sSearch}%")
      else
        array = array.where("seguros.numero_contrato LIKE ?", "%#{sSearch}%")
                     .or(array.where("seguros.factura_numero LIKE ?", "%#{sSearch}%"))
                     .or(array.where("suppliers.name LIKE ?", "%#{sSearch}%"))
      end
    end
    array
  end

  def self.set_columns
    h = ApplicationController.helpers
    [h.get_column(self, 'numero_contrato'), h.get_column(self, 'factura_numero'), h.get_column(self, 'suppliers')]
  end

  def self.to_csv(is_low = false)
    columns_title = %w(numero_contrato suppliers numero_factura fecha_inicio_vigencia fecha_fin_vigencia estado nro_activos )
    CSV.generate do |csv|
      csv << columns_title.map { |c| self.human_attribute_name(c) }
      all.each do |seguro|
        a = []
        a.push(seguro.numero_contrato)
        a.push(seguro.proveedor_nombre)
        a.push(seguro.factura_numero)
        a.push(seguro.fecha_inicio_vigencia.present? ? I18n.l(seguro.fecha_inicio_vigencia) : '')
        a.push(seguro.fecha_fin_vigencia.present? ? I18n.l(seguro.fecha_fin_vigencia) : '')
        a.push(seguro.estado)
        a.push(seguro.cantidad_activos)
        csv << a
      end
    end
  end

  def incorporaciones_json
    respuesta = []
    incorporaciones.order(state: :desc, created_at: :desc).each do |inc|
      activos_ids = inc.assets.try(:ids)
      activos = Asset.todos.where(id: activos_ids).order(:code)
      sumatoria = activos.inject(0.0) { |total, activo| total + activo.precio }
      resumen = activos.select("accounts.name as nombre, count(accounts.name) as cantidad, sum(assets.precio) as sumatoria")
                       .group("accounts.name").order("nombre")
      sumatoria_resumen = resumen.inject(0.0) { |total, cuenta| total + cuenta.sumatoria }
      respuesta << {
        titulo: 'Incorporación',
        seguro: SeguroSerializer.new(inc),
        activos: ActiveModel::ArraySerializer.new(activos, each_serializer: AssetSerializer),
        sumatoria: sumatoria,
        resumen: ActiveModel::ArraySerializer.new(resumen, each_serializer: ResumenSerializer),
        sumatoria_resumen: sumatoria_resumen,
        urls: {
          asegurar: asegurar_seguro_url(inc),
          activos: activos_seguro_url(inc, format: :pdf),
          resumen: resumen_seguro_url(inc, format: :pdf)
        }
      }
    end
    respuesta
  end

  def activos_sin_seguro
    seguros_ids = [self.id] + self.incorporaciones.pluck(:id)
    activos_ids = Asset.joins(:seguros).where(seguros: {id: seguros_ids}).ids
    Asset.todos.where.not(id: activos_ids).order(:code)
  end
end

app/controllers/api/v1/seguros_controller.rb
module Api
  module V1
    class SegurosController < ApplicationController
      before_action :set_usuario, only: [:create]
      before_action :set_seguro, only: [:update]

      respond_to :json

      def create
        @seguro = Seguro.new(seguro_params)
        @seguro.user = @usuario
        respond_to do |format|
          if @seguro.save
            format.json { render json: @seguro, root: false, status: :created }
          else
            format.json { render json: @seguro.errors, status: :unprocessable_entity }
          end
        end
      end

      def update
        respond_to do |format|
          if @seguro.update(seguro_params)
            @seguro.asegurar! if @seguro.cotizado?
            format.html { redirect_to @seguro, notice: 'El Seguro fue actualizado exitosamente.' }
            format.json { render json: @seguro, root: false, status: :created }
          else
            format.html { render action: 'new' }
            format.json { render json: @seguro.errors, status: :unprocessable_entity }
          end
        end
      end

      private

      def set_seguro
        @seguro = Seguro.find(params[:id])
      end

      def set_usuario
        @usuario = current_user
      end

      def seguro_params
        params.require(:seguro)
              .permit(:supplier_id, :user_id, :seguro_id, :numero_contrato,
                      :factura_numero, :factura_autorizacion, :factura_fecha,
                      :factura_monto, :numero_poliza, :fecha_inicio_vigencia,
                      :fecha_fin_vigencia, :baja_logica, :tipo, asset_ids: [])
      end
    end
  end
end

app/helpers/seguros_helper.rb
module SegurosHelper
  def seguros_datos(seguro)
    datos = []
    seguro_padre = seguro.seguro || seguro
    if seguro_padre.numero_poliza
      datos << ['Póliza', seguro_padre.numero_poliza]
    end
    if seguro.numero_contrato
      datos << ['Número de contrato', seguro.numero_contrato]
    end
    if seguro_padre.fecha_inicio_vigencia
      datos << ['Desde', l(seguro_padre.fecha_inicio_vigencia, format: :version)]
    end
    if seguro_padre.fecha_fin_vigencia
      datos << ['Hasta', l(seguro_padre.fecha_fin_vigencia, format: :version)]
    end
    if seguro.proveedor_nombre.present?
      datos << ['Proveedor', seguro.proveedor_nombre]
    end
    if seguro.proveedor_nit.present?
      datos << ['NIT', seguro.proveedor_nit]
    end
    if seguro.proveedor_telefono.present?
      datos << ['Teléfono(s)', seguro.proveedor_telefono]
    end
    if seguro.factura_numero
      datos << ['Número de factura', seguro.factura_numero]
    end
    if seguro.factura_autorizacion
      datos << ['Número de autorización', seguro.factura_autorizacion]
    end
    if seguro.factura_fecha
      datos << ['Fecha factura', l(seguro.factura_fecha)]
    end
    if seguro.factura_monto
      datos << ['Monto factura', seguro.factura_monto]
    end
    datos
  end
end

app/views/seguros/_encabezado.haml
- if seguro.state == 'cotizado'
  %h3 Listado de Activos Fijos
- elsif seguro.state == 'asegurado'
  %h3
    Activos Fijos con Seguro
    .pull-right.text-muted
      = seguro.seguro ? 'INCORPORACIÓN' : 'CONTRATO'

  - seguro_padre = seguro.seguro || seguro
  - datos = seguros_datos(seguro)
  - division = (datos.length / 2.0).round
  
  %table.table.table-condensed.valorado-sin-borde
    %tbody
      - (0...division).each do |i|
        %tr
          %th.text-right= datos[i].first
          %td= datos[i].second
          - if datos[i+division].present?
            %th.text-right= datos[i+division].first
            %td= datos[i+division].second
          - else
            %th
            %td

app/views/seguros/_form.html.haml
= simple_form_for @seguro do |f|
  - if @seguro.errors.any?
    #error_explanation
      %h2= "#{pluralize(@seguro.errors.count, "error")} prohibited this seguro from being saved:"
      %ul
        - @seguro.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.association :supplier
  .field
    = f.association :user
  .field
    = f.input :numero_contrato
  .field
    = f.input :factura_numero
  .field
    = f.input :factura_autorizacion
  .field
    = f.date_select :factura_fecha
  .field
    = f.date_select :fecha_inicio_vigencia
  .field
    = f.date_select :fecha_fin_vigencia
  .actions
    = f.submit 'Save'

app/views/seguros/_seguros.html.haml
%th= Seguro.human_attribute_name("tipo")
%th= Seguro.human_attribute_name("numero_poliza")
%th= Seguro.human_attribute_name("numero_contrato")
%th= Seguro.human_attribute_name("suppliers")
%th= Seguro.human_attribute_name("fecha_inicio_vigencia")
%th= Seguro.human_attribute_name("fecha_fin_vigencia")
%th= Seguro.human_attribute_name("estado")
%th= Seguro.human_attribute_name("nro_assets")

app/views/seguros/activos.pdf.haml
= render 'encabezado', seguro: @seguro

%table.table.table-striped.table-condensed.table-bordered.alineacion-media.valorado
  %thead
    %tr
      %th
      %th.text-center Código
      %th.col-xs-7 Descripción
      %th Cuenta
      %th.text-right Precio
  %tbody
    - if @activos.present?
      - @activos.each_with_index do |activo, index|
        %tr
          %td= index + 1
          %td.text-center= activo.code
          %td= activo.description
          %td= activo.cuenta
          %td.number= activo.precio
      %tr
        %th{ colspan: "3" }
        %th.text-right Total
        %th.number= @sumatoria

app/views/seguros/asegurar.html.haml
= react_component 'SeguroAsegurar', data: @data

app/views/seguros/edit.html.haml
= react_component 'SeguroEditar', data: @data

app/views/seguros/index.html.haml
%h1 Listing seguros

%table
  %tr
    %th Supplier
    %th User
    %th Numero contrato
    %th Factura numero
    %th Factura autorizacion
    %th Factura fecha
    %th Fecha inicio vigencia
    %th Fecha fin vigencia
    %th Baja logica
    %th
    %th
    %th

  - @seguros.each do |seguro|
    %tr
      %td= seguro.supplier
      %td= seguro.user
      %td= seguro.numero_contrato
      %td= seguro.factura_numero
      %td= seguro.factura_autorizacion
      %td= seguro.factura_fecha
      %td= seguro.fecha_inicio_vigencia
      %td= seguro.fecha_fin_vigencia
      %td= seguro.baja_logica
      %td= link_to 'Show', seguro
      %td= link_to 'Edit', edit_seguro_path(seguro)
      %td= link_to 'Destroy', seguro, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Seguro', new_seguro_path

app/views/seguros/index.pdf.haml
.title_pdf
  %h3= t("#{controller_name}.title.title")

%table.table.table-condensed.table-bordered.valorado
  %thead
    %tr
      %th= Seguro.human_attribute_name("numero_poliza")
      %th= Seguro.human_attribute_name("numero_contrato")
      %th= Seguro.human_attribute_name("suppliers")
      %th.text-center= Seguro.human_attribute_name("fecha_inicio_vigencia")
      %th.text-center= Seguro.human_attribute_name("fecha_fin_vigencia")
      %th= Seguro.human_attribute_name("estado")
      %th.text-right= Seguro.human_attribute_name("nro_activos")
  %tbody
    - @array.each_with_index do |seguro, index|
      %tr
        %td= seguro.numero_contrato
        %td= seguro.proveedor_nombre
        %td= seguro.factura_numero
        %td.text-center= seguro.fecha_inicio_vigencia.present? ? I18n.l(seguro.fecha_inicio_vigencia) : ''
        %td.text-center= seguro.fecha_fin_vigencia.present? ? I18n.l(seguro.fecha_fin_vigencia) : ''
        %td= seguro.estado
        %td.text-right= seguro.cantidad_activos

app/views/seguros/new.html.haml
= react_component 'SeguroNuevo', data: @data

app/views/seguros/resumen.pdf.haml
= render 'encabezado', seguro: @seguro

%table.table.table-striped.table-condensed.table-bordered.alineacion-media.valorado
  %thead
    %tr
      %th
      %th Cuenta
      %th.text-right Cantidad
      %th.text-right Monto
  %tbody
    - if @resumen.present?
      - sumatoria_cantidad = 0
      - @resumen.each_with_index do |cuenta, index|
        %tr
          %td= index + 1
          %td= cuenta.nombre
          %td.number= cuenta.cantidad
          %td.number= number_with_delimiter cuenta.sumatoria
        - sumatoria_cantidad += cuenta.cantidad
      %tr
        %th
        %th.text-right Total
        %th.number= sumatoria_cantidad
        %th.number= number_with_delimiter @sumatoria_resumen

app/views/seguros/show.html.haml
= react_component 'SeguroDesplegar', data: @data